const widgetListCase = [
    {
        "id": "input31621",
        "icon": "text-field",
        "type": "input",
        "options": {
            "name": "input31621",
            "size": "",
            "type": "text",
            "label": "用户名",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "onInput": "",
            "disabled": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "maxLength": null,
            "minLength": null,
            "onCreated": "",
            "onMounted": "",
            "buttonIcon": "el-icon-search",
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "prefixIcon": "",
            "suffixIcon": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": [],
            "labelHidden": false,
            "placeholder": "",
            "appendButton": false,
            "defaultValue": "",
            "labelTooltip": null,
            "showPassword": false,
            "showWordLimit": false,
            "labelIconClass": null,
            "validationHint": "",
            "labelIconPosition": "rear",
            "appendButtonDisabled": false
        },
        "formItemFlag": true
    },
    {
        "id": "input22951",
        "icon": "text-field",
        "type": "input",
        "options": {
            "name": "input22951",
            "size": "",
            "type": "password",
            "label": "密码",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "onInput": "",
            "disabled": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "maxLength": null,
            "minLength": null,
            "onCreated": "",
            "onMounted": "",
            "buttonIcon": "el-icon-search",
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "prefixIcon": "",
            "suffixIcon": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "appendButton": false,
            "defaultValue": "",
            "labelTooltip": null,
            "showPassword": false,
            "showWordLimit": false,
            "labelIconClass": null,
            "validationHint": "",
            "labelIconPosition": "rear",
            "appendButtonDisabled": false
        },
        "formItemFlag": true
    },
    {
        "id": "number50376",
        "icon": "number-field",
        "type": "number",
        "options": {
            "max": 100,
            "min": 0,
            "name": "number50376",
            "size": "",
            "step": 1,
            "label": "年龄",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "disabled": false,
            "onChange": "",
            "required": false,
            "onCreated": "",
            "onMounted": "",
            "precision": 0,
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "validation": "number",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "defaultValue": 0,
            "labelTooltip": null,
            "labelIconClass": null,
            "validationHint": "",
            "controlsPosition": "right",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "input26929",
        "icon": "text-field",
        "type": "input",
        "options": {
            "name": "input26929",
            "size": "",
            "type": "text",
            "label": "邮箱",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "onInput": "",
            "disabled": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "maxLength": null,
            "minLength": null,
            "onCreated": "",
            "onMounted": "",
            "buttonIcon": "el-icon-search",
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "prefixIcon": "",
            "suffixIcon": "",
            "validation": "email",
            "columnWidth": "200px",
            "customClass": [],
            "labelHidden": false,
            "placeholder": "",
            "appendButton": false,
            "defaultValue": "",
            "labelTooltip": null,
            "showPassword": false,
            "showWordLimit": false,
            "labelIconClass": null,
            "validationHint": "请输入正确邮箱",
            "labelIconPosition": "rear",
            "appendButtonDisabled": false
        },
        "formItemFlag": true
    },
    {
        "id": "time84549",
        "icon": "time-field",
        "type": "time",
        "options": {
            "name": "time84549",
            "size": "",
            "label": "时间",
            "format": "HH:mm:ss",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "disabled": false,
            "editable": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "onCreated": "",
            "onMounted": "",
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "defaultValue": null,
            "labelTooltip": null,
            "labelIconClass": null,
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "date29628",
        "icon": "date-field",
        "type": "date",
        "options": {
            "name": "date29628",
            "size": "",
            "type": "date",
            "label": "日期",
            "format": "yyyy-MM-dd",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "disabled": false,
            "editable": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "onCreated": "",
            "onMounted": "",
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "valueFormat": "yyyy-MM-dd",
            "defaultValue": null,
            "labelTooltip": null,
            "labelIconClass": null,
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    }
]

const widgetListCase2 = [
    {
        "id": "radio69782",
        "icon": "radio-field",
        "type": "radio",
        "options": {
            "name": "radio69782",
            "size": "",
            "label": "radio",
            "border": false,
            "hidden": false,
            "disabled": false,
            "onChange": "",
            "required": false,
            "onCreated": "",
            "onMounted": "",
            "labelAlign": "label-left-align",
            "labelWidth": null,
            "onValidate": "",
            "validation": "",
            "buttonStyle": false,
            "columnWidth": "200px",
            "customClass": [],
            "labelHidden": false,
            "optionItems": [
                {
                    "label": "radio 1",
                    "value": 1
                },
                {
                    "label": "radio 2",
                    "value": 2
                },
                {
                    "label": "radio 3",
                    "value": 3
                }
            ],
            "defaultValue": 1,
            "displayStyle": "inline",
            "labelTooltip": null,
            "labelIconClass": null,
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "checkbox79755",
        "icon": "checkbox-field",
        "type": "checkbox",
        "options": {
            "name": "checkbox79755",
            "size": "",
            "label": "checkbox",
            "border": false,
            "hidden": false,
            "disabled": false,
            "onChange": "",
            "required": false,
            "onCreated": "",
            "onMounted": "",
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "validation": "",
            "buttonStyle": false,
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "optionItems": [
                {
                    "label": "check 1",
                    "value": 1
                },
                {
                    "label": "check 2",
                    "value": 2
                },
                {
                    "label": "check 3",
                    "value": 3
                }
            ],
            "defaultValue": [
                1
            ],
            "displayStyle": "inline",
            "labelTooltip": null,
            "labelIconClass": null,
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    }
]

const widgetListCase3 = [
    {
        "id": "input31621",
        "icon": "text-field",
        "type": "input",
        "options": {
            "name": "input31621",
            "size": "",
            "type": "text",
            "label": "用户名",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "onInput": "",
            "disabled": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "onCreated": "",
            "onMounted": "",
            "buttonIcon": "el-icon-search",
            "labelAlign": "",
            "onValidate": "",
            "prefixIcon": "",
            "suffixIcon": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": [],
            "labelHidden": false,
            "placeholder": "",
            "appendButton": false,
            "defaultValue": "",
            "showPassword": false,
            "showWordLimit": false,
            "validationHint": "",
            "labelIconPosition": "rear",
            "appendButtonDisabled": false
        },
        "formItemFlag": true
    },
    {
        "id": "input22951",
        "icon": "text-field",
        "type": "input",
        "options": {
            "name": "input22951",
            "size": "",
            "type": "password",
            "label": "密码",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "onInput": "",
            "disabled": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "onCreated": "",
            "onMounted": "",
            "buttonIcon": "el-icon-search",
            "labelAlign": "",
            "onValidate": "",
            "prefixIcon": "",
            "suffixIcon": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "appendButton": false,
            "defaultValue": "",
            "showPassword": false,
            "showWordLimit": false,
            "validationHint": "",
            "labelIconPosition": "rear",
            "appendButtonDisabled": false
        },
        "formItemFlag": true
    },
    {
        "id": "number50376",
        "icon": "number-field",
        "type": "number",
        "options": {
            "max": 100,
            "min": 0,
            "name": "number50376",
            "size": "",
            "step": 1,
            "label": "年龄",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "disabled": false,
            "onChange": "",
            "required": false,
            "onCreated": "",
            "onMounted": "",
            "precision": 0,
            "labelAlign": "",
            "onValidate": "",
            "validation": "number",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "defaultValue": 0,
            "validationHint": "",
            "controlsPosition": "right",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "input26929",
        "icon": "text-field",
        "type": "input",
        "options": {
            "name": "input26929",
            "size": "",
            "type": "text",
            "label": "邮箱",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "onInput": "",
            "disabled": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "onCreated": "",
            "onMounted": "",
            "buttonIcon": "el-icon-search",
            "labelAlign": "",
            "onValidate": "",
            "prefixIcon": "",
            "suffixIcon": "",
            "validation": "email",
            "columnWidth": "200px",
            "customClass": [],
            "labelHidden": false,
            "placeholder": "",
            "appendButton": false,
            "defaultValue": "",
            "showPassword": false,
            "showWordLimit": false,
            "validationHint": "请输入正确邮箱",
            "labelIconPosition": "rear",
            "appendButtonDisabled": false
        },
        "formItemFlag": true
    },
    {
        "id": "time84549",
        "icon": "time-field",
        "type": "time",
        "options": {
            "name": "time84549",
            "size": "",
            "label": "时间",
            "format": "HH:mm:ss",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "disabled": false,
            "editable": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "onCreated": "",
            "onMounted": "",
            "labelAlign": "",
            "onValidate": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "date29628",
        "icon": "date-field",
        "type": "date",
        "options": {
            "name": "date29628",
            "size": "",
            "type": "date",
            "label": "日期",
            "format": "yyyy-MM-dd",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "disabled": false,
            "editable": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "onCreated": "",
            "onMounted": "",
            "labelAlign": "",
            "onValidate": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "valueFormat": "yyyy-MM-dd",
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "radio97981",
        "icon": "radio-field",
        "type": "radio",
        "options": {
            "name": "radio97981",
            "size": "",
            "label": "radio",
            "border": false,
            "hidden": false,
            "disabled": false,
            "onChange": "",
            "required": false,
            "onCreated": "",
            "onMounted": "",
            "labelAlign": "",
            "onValidate": "",
            "validation": "",
            "buttonStyle": false,
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "optionItems": [
                {
                    "label": "radio 1",
                    "value": 1
                },
                {
                    "label": "radio 2",
                    "value": 2
                },
                {
                    "label": "radio 3",
                    "value": 3
                }
            ],
            "displayStyle": "inline",
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "checkbox57516",
        "icon": "checkbox-field",
        "type": "checkbox",
        "options": {
            "name": "checkbox57516",
            "size": "",
            "label": "checkbox",
            "border": false,
            "hidden": false,
            "disabled": false,
            "onChange": "",
            "required": false,
            "onCreated": "",
            "onMounted": "",
            "labelAlign": "",
            "onValidate": "",
            "validation": "",
            "buttonStyle": false,
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "optionItems": [
                {
                    "label": "check 1",
                    "value": 1
                },
                {
                    "label": "check 2",
                    "value": 2
                },
                {
                    "label": "check 3",
                    "value": 3
                }
            ],
            "defaultValue": [],
            "displayStyle": "inline",
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    }
]

const widgetListCase4=[
    {
        "id": "textarea50959",
        "icon": "textarea-field",
        "type": "textarea",
        "options": {
            "name": "textarea50959",
            "rows": 3,
            "size": "",
            "label": "textarea",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "onInput": "",
            "disabled": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "onCreated": "",
            "onMounted": "",
            "labelAlign": "",
            "onValidate": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": [],
            "labelHidden": false,
            "placeholder": "",
            "defaultValue": "",
            "showWordLimit": false,
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "select71599",
        "icon": "select-field",
        "type": "select",
        "options": {
            "name": "select71599",
            "size": "",
            "label": "select",
            "hidden": false,
            "onBlur": "",
            "remote": false,
            "onFocus": "",
            "disabled": false,
            "multiple": false,
            "onChange": "",
            "required": false,
            "clearable": true,
            "onCreated": "",
            "onMounted": "",
            "filterable": false,
            "labelAlign": "",
            "onValidate": "",
            "validation": "",
            "allowCreate": false,
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "optionItems": [
                {
                    "label": "select 1",
                    "value": 1
                },
                {
                    "label": "select 2",
                    "value": 2
                },
                {
                    "label": "select 3",
                    "value": 3
                }
            ],
            "placeholder": "",
            "defaultValue": "",
            "multipleLimit": 0,
            "onRemoteQuery": "",
            "validationHint": "",
            "automaticDropdown": false,
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "switch53247",
        "icon": "switch-field",
        "type": "switch",
        "options": {
            "name": "switch53247",
            "label": "switch",
            "hidden": false,
            "disabled": false,
            "onChange": "",
            "onCreated": "",
            "onMounted": "",
            "activeText": "",
            "labelAlign": "",
            "onValidate": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "switchWidth": 40,
            "defaultValue": false,
            "inactiveText": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "rate23245",
        "icon": "rate-field",
        "type": "rate",
        "options": {
            "max": 5,
            "name": "rate23245",
            "label": "rate",
            "hidden": false,
            "disabled": false,
            "onChange": "",
            "required": false,
            "showText": false,
            "allowHalf": false,
            "onCreated": "",
            "onMounted": "",
            "showScore": false,
            "labelAlign": "",
            "onValidate": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "defaultValue": 0,
            "lowThreshold": 2,
            "highThreshold": 4,
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "slider104722",
        "icon": "slider-field",
        "type": "slider",
        "options": {
            "max": 100,
            "min": 0,
            "name": "slider104722",
            "size": "",
            "step": 10,
            "label": "slider",
            "range": false,
            "hidden": false,
            "disabled": false,
            "onChange": "",
            "required": false,
            "onCreated": "",
            "onMounted": "",
            "showStops": true,
            "labelAlign": "",
            "onValidate": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "statictext53335",
        "icon": "static-text",
        "type": "static-text",
        "options": {
            "name": "statictext53335",
            "label": "static-text",
            "hidden": false,
            "onCreated": "",
            "onMounted": "",
            "columnWidth": "200px",
            "customClass": "",
            "textContent": "static text"
        },
        "formItemFlag": false
    },
    {
        "id": "divider19887",
        "icon": "divider",
        "type": "divider",
        "options": {
            "name": "divider19887",
            "label": "divider",
            "hidden": false,
            "direction": "horizontal",
            "onCreated": "",
            "onMounted": "",
            "columnWidth": "200px",
            "customClass": "",
            "contentPosition": "center"
        },
        "formItemFlag": false
    }
]

const widgetListCase5=[
    {
        "id": "input31621",
        "icon": "text-field",
        "type": "input",
        "options": {
            "name": "input31621",
            "size": "",
            "type": "text",
            "label": "用户名",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "onInput": "",
            "disabled": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "maxLength": null,
            "minLength": null,
            "onCreated": "",
            "onMounted": "",
            "buttonIcon": "el-icon-search",
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "prefixIcon": "",
            "suffixIcon": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": [],
            "labelHidden": false,
            "placeholder": "",
            "appendButton": false,
            "defaultValue": "",
            "labelTooltip": null,
            "showPassword": false,
            "showWordLimit": false,
            "labelIconClass": null,
            "validationHint": "",
            "labelIconPosition": "rear",
            "appendButtonDisabled": false
        },
        "formItemFlag": true
    },
    {
        "id": "input22951",
        "icon": "text-field",
        "type": "input",
        "options": {
            "name": "input22951",
            "size": "",
            "type": "password",
            "label": "密码",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "onInput": "",
            "disabled": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "maxLength": null,
            "minLength": null,
            "onCreated": "",
            "onMounted": "",
            "buttonIcon": "el-icon-search",
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "prefixIcon": "",
            "suffixIcon": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "appendButton": false,
            "defaultValue": "",
            "labelTooltip": null,
            "showPassword": false,
            "showWordLimit": false,
            "labelIconClass": null,
            "validationHint": "",
            "labelIconPosition": "rear",
            "appendButtonDisabled": false
        },
        "formItemFlag": true
    },
    {
        "id": "number50376",
        "icon": "number-field",
        "type": "number",
        "options": {
            "max": 100,
            "min": 0,
            "name": "number50376",
            "size": "",
            "step": 1,
            "label": "年龄",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "disabled": false,
            "onChange": "",
            "required": false,
            "onCreated": "",
            "onMounted": "",
            "precision": 0,
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "validation": "number",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "defaultValue": 0,
            "labelTooltip": null,
            "labelIconClass": null,
            "validationHint": "",
            "controlsPosition": "right",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "input26929",
        "icon": "text-field",
        "type": "input",
        "options": {
            "name": "input26929",
            "size": "",
            "type": "text",
            "label": "邮箱",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "onInput": "",
            "disabled": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "maxLength": null,
            "minLength": null,
            "onCreated": "",
            "onMounted": "",
            "buttonIcon": "el-icon-search",
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "prefixIcon": "",
            "suffixIcon": "",
            "validation": "email",
            "columnWidth": "200px",
            "customClass": [],
            "labelHidden": false,
            "placeholder": "",
            "appendButton": false,
            "defaultValue": "",
            "labelTooltip": null,
            "showPassword": false,
            "showWordLimit": false,
            "labelIconClass": null,
            "validationHint": "请输入正确邮箱",
            "labelIconPosition": "rear",
            "appendButtonDisabled": false
        },
        "formItemFlag": true
    },
    {
        "id": "time84549",
        "icon": "time-field",
        "type": "time",
        "options": {
            "name": "time84549",
            "size": "",
            "label": "时间",
            "format": "HH:mm:ss",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "disabled": false,
            "editable": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "onCreated": "",
            "onMounted": "",
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "defaultValue": null,
            "labelTooltip": null,
            "labelIconClass": null,
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    },
    {
        "id": "date29628",
        "icon": "date-field",
        "type": "date",
        "options": {
            "name": "date29628",
            "size": "",
            "type": "date",
            "label": "日期",
            "format": "yyyy-MM-dd",
            "hidden": false,
            "onBlur": "",
            "onFocus": "",
            "disabled": false,
            "editable": false,
            "onChange": "",
            "readonly": false,
            "required": false,
            "clearable": true,
            "onCreated": "",
            "onMounted": "",
            "labelAlign": "",
            "labelWidth": null,
            "onValidate": "",
            "validation": "",
            "columnWidth": "200px",
            "customClass": "",
            "labelHidden": false,
            "placeholder": "",
            "valueFormat": "yyyy-MM-dd",
            "defaultValue": null,
            "labelTooltip": null,
            "labelIconClass": null,
            "validationHint": "",
            "labelIconPosition": "rear"
        },
        "formItemFlag": true
    }
]
export {widgetListCase, widgetListCase2,widgetListCase3,widgetListCase4,widgetListCase5}